### ISSUE TITLE
Upload from Local Storage

### ISSUE THREAD

**Issue by voreisthescore** [slynn1324/tinypin#1]
Would love to have this present in the web UI, so that we could either drag and drop local images and/or with a file picker. Image URL is great but in the interests of migrating from existing systems + images from services/sites that are no longer around is good for posterity.

**Comment by slynn1324** [comment]
Didn't have time to look at this in a long while - but had some time to poke around today.  This should be working in v0.2.

There should be a file input in the add pin dialog to upload single files.   To add multiple files, you can also drag-and-drop directly to a board page.
